# Numpy Basics

In [2]:
import numpy as np

In [3]:
arr1 = [1, 2, 3, 4, 5]
arr = np.array([1, 2, 3, 4, 5])
type(arr)

numpy.ndarray

In [4]:
arr.shape

(5,)

In [5]:
l1 = [1, 2, 3, 4, 5]
l2 = [6, 7, 8, 9, 10]
arr1 = np.array([l1, l2])
print(arr1)
arr1.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


(2, 5)

In [6]:
arr1.reshape(5, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [8]:
arr[1]
arr1[1][3]

np.int64(9)

In [10]:
arr[1:]
arr1[1:, 2:]

array([[ 8,  9, 10]])

In [12]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [14]:
# copy function and broadcasting
arr3 = arr.copy()
arr[2:] = 100
print(arr)
print(arr3)

[  1   2 100 100 100]
[1 2 3 4 5]


In [15]:
val = 2
arr < val

array([ True, False, False, False, False])

In [16]:
arr*val

array([  2,   4, 200, 200, 200])

In [18]:
arr[arr > val]

array([100, 100, 100])

In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
np.ones(5, dtype=int)

array([1, 1, 1, 1, 1])

In [21]:
np.ones((2, 5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [22]:
np.random.rand(3, 3)

array([[4.67448283e-05, 3.57524403e-01, 2.09868900e-02],
       [8.88580897e-01, 9.00706160e-01, 3.94204702e-01],
       [5.39205375e-01, 7.51186363e-01, 7.68366908e-01]])